#!/usr/bin/env bash
# Display PID and full path of all processes whose name contains 'bash'
ps -C bash -o pid= | while read pid; do
    full_path=$(readlink -f /proc/"$pid"/exe 2>/dev/null)
    echo "$pid $full_path"
done
