#!/usr/bin/env bash
# Sends SIGTERM to the 7-highlander process

# Find all PIDs of 7-highlander
pids=$(pgrep -x 7-highlander)

# Send SIGTERM to each PID found
for pid in $pids; do
    kill -SIGTERM "$pid"
done
