#!/bin/bash
# File: 7-highlander

# Function to handle SIGTERM
sigterm_handler() {
    echo "I am invincible!!!"
}

# Trap SIGTERM and call the handler
trap sigterm_handler SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
